// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llqrpvxpduvwcxsavlnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscXJwdnhwZHV2d2N4c2F2bG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzcwODAsImV4cCI6MjA1MTIxMzA4MH0.fPahu5927EVE4lqQcK9sp-6UfxA09tj6bHQpwOLpZ8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);